//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "3.3578.1869.gcc1dc0f";
        public const int CEF_VERSION_MAJOR = 3;
        public const int CEF_COMMIT_NUMBER = 1869;
        public const string CEF_COMMIT_HASH = "cc1dc0f59d87d5f14b09c451356ca6e3fb576154";
        
        public const int CHROME_VERSION_MAJOR = 71;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 3578;
        public const int CHROME_VERSION_PATCH = 98;
        
        public const string CEF_API_HASH_UNIVERSAL = "161352dfc6601b5f28b409b6035c95ec4d21f7a0";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "864498db9f12dd977766dc74abc56f198b39e2ce";
        public const string CEF_API_HASH_PLATFORM_MACOSX = "32247df6e90b9555e16862e75885d7e157852156";
        public const string CEF_API_HASH_PLATFORM_LINUX = "a6fa42b9e296d27d524fc561060368e0209cef8b";
    }
}
