//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "84.4.1+gfdc7504+chromium-84.0.4147.105";
        public const int CEF_VERSION_MAJOR = 84;
        public const int CEF_COMMIT_NUMBER = 2231;
        public const string CEF_COMMIT_HASH = "fdc75046316a1c9366143df25e163e0c634a0022";
        
        public const int CHROME_VERSION_MAJOR = 84;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 4147;
        public const int CHROME_VERSION_PATCH = 105;
        
        public const string CEF_API_HASH_UNIVERSAL = "63365efe2e93a4e7cc789cbb8f618d61c92c1b6d";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "726d42ca7d92188542b433d88d17a87af5b53c05";
        public const string CEF_API_HASH_PLATFORM_MACOSX = "1c8a413434b592d388446e66b54a3f0bfc0d6fff";
        public const string CEF_API_HASH_PLATFORM_LINUX = "13f7e0e86daab3b1a08d8a31103fc93e45cc508f";
    }
}
